import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import PageTransition from "@/components/PageTransition";
import WordByWordText from "@/components/WordByWordText";

const Budgeting = () => {
  const navigate = useNavigate();

  const budgetingText = `Let's be real—money disappears faster than you can say "TikTok Shop." One minute you've got $200 from your birthday, and the next minute you're wondering where it all went. Sound familiar? Welcome to the world where budgeting isn't just for adults—it's your secret weapon for actually keeping money in your pocket.

A budget is basically a plan for your money before you spend it. Think of it like a GPS for your finances: it tells you where your money should go so you don't end up lost (and broke) somewhere you didn't plan to be. Most teens think budgeting means "never buying anything fun," but that's completely wrong. Smart budgeting actually helps you afford the things you want while still saving for bigger goals.

The 50/30/20 rule is a great starting point for beginners. Here's how it works: 50% of your money goes to needs (things you absolutely have to buy), 30% goes to wants (the fun stuff), and 20% goes to savings. So if you earn $100 from a part-time job, $50 covers necessities like lunch money or school supplies, $30 is for entertainment like movies or clothes, and $20 goes straight into savings.

But here's where it gets interesting—most teens don't realize how much they actually spend on small things. That daily energy drink, those in-app purchases, or grabbing food with friends can add up to hundreds of dollars monthly. Start tracking everything for just one week. Use your phone's notes app or a simple budgeting app like Mint or YNAB (You Need A Budget). You'll probably be shocked at where your money actually goes.

The key to successful budgeting is being realistic about your spending habits. If you know you're going to buy coffee three times a week, budget for it instead of pretending you won't. If you're saving for something specific—like a new phone, concert tickets, or a car—calculate how much you need to save each month to reach that goal.

Emergency funds might sound boring, but they're game-changers. Even setting aside $5-10 per week builds up quickly and saves you from having to ask your parents for money when unexpected things happen. Plus, having your own money gives you independence and confidence in making decisions.

Budgeting apps can make this process way easier. Apps like PiggyBot, Greenlight, or even your bank's app can help track spending automatically. Many of these apps send notifications when you're close to spending limits in different categories, which helps you stay on track without constantly calculating.

The best part about learning budgeting now? You're developing a skill that will literally save you thousands of dollars throughout your life. Adults who never learned these basics often struggle with debt, can't afford things they really want, and stress about money constantly. By mastering budgeting as a teen, you're setting yourself up for financial freedom later.

At Spendora, we'll walk you through creating your first real budget, choosing the right apps and tools, and developing habits that actually stick. You'll leave knowing exactly how to manage your money, save for your goals, and still have fun—without the stress of wondering where your money went.`;

  return (
    <PageTransition transitionType="fade">
      <div className="min-h-screen bg-white dark:bg-gray-900 transition-colors duration-300">
        <div className="container mx-auto px-6 py-12">
          <div className="max-w-4xl mx-auto">
            <Button 
              variant="ghost" 
              onClick={() => navigate('/')}
              className="mb-8 flex items-center space-x-2 hover:bg-gray-100 dark:hover:bg-gray-800"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Home</span>
            </Button>

            <div className="bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800 rounded-lg p-6 mb-8">
              <h2 className="text-xl font-semibold text-orange-800 dark:text-orange-200 mb-2">
                🤖 Temporary AI Content
              </h2>
              <p className="text-orange-700 dark:text-orange-300">
                This content is temporarily generated by AI to give you a preview. A human will review and write a better version soon!
              </p>
            </div>

            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-8">
              Budgeting & Personal Finance
            </h1>

            <div className="prose prose-lg max-w-none dark:prose-invert">
              <WordByWordText 
                text={budgetingText}
                className="text-lg text-gray-700 dark:text-gray-300 leading-relaxed"
                delay={100}
                wordDelay={200}
              />
            </div>
          </div>
        </div>
      </div>
    </PageTransition>
  );
};

export default Budgeting;